version: '3'

networks:
  ingress:
#   driver: bridge
    external: true
  keycloak:
#   driver: bridge
    external: true

services:
  nginx-ingress:
    image: nginx:1.19.6
    container_name: nginx-ingress
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./sslkeys/:/sslkeys/
    #NOTE : TLS key's path for HTTPS
    # - <host ssl_certificate key's path> : <nginx.conf ssl_certificate key's path>
    # - <host ssl_certificate_key key's path> : <nginx.conf  ssl_certificate_key key's path>
    networks:
      - ingress
      - keycloak
    hostname: nginx
    ports:
      - "8080:8080"
      - "8443:8443"
      - "80:80"
      - "443:443"
    #depends_on:
    #  - keycloak
    command: ["nginx", "-g", "daemon off;"]
    restart: unless-stopped

